/**
 * Centralized system prompt generation for AI providers
 * This module consolidates all system prompt logic to make it easier to manage and maintain
 */

import { ResponseMode } from "@/lib/db";

// Common instruction to strictly forbid self-prefixing
export const PREFIX_FORBIDDEN_INSTRUCTION = `
STRICTLY FORBIDDEN:
- NEVER, under any circumstances, prefix your own response with your name or any label.
- NEVER start your response with your name in brackets.
- Just start your response with the actual content.
- The UI handles displaying your name to the user. This is a MANDATORY rule.`;

// Common formatting rules
const FORMATTING_RULES = `FORMATTING RULES:
- Use proper Markdown syntax (headers, bold, italic, lists, code blocks)
- For currency/dollar amounts, write $100 normally (dollar signs are safe)
- For mathematical expressions, use code blocks or plain text (e.g., x^2, (a + b)^2, sqrt(x))
- Never use LaTeX or math delimiters like $ $ or $$ $$
- For complex math, use a code block with clear notation
- Never use literal \\n for line breaks - use actual newlines
- Ensure proper spacing between paragraphs and sections`;

// Multi-agent context instructions
const MULTI_AGENT_CONTEXT = `MULTI-AGENT CONTEXT:
- You are part of a multi-agent conversation.
- Previous assistant messages may have been generated by different models.
- These messages are prefixed with their model name, e.g., "[Gemini 3 Flash]: ..." or "[Grok 4.1 Fast]: ...".
- Acknowledge this context if the user asks about multiple agents or specific previous responses.`;

/**
 * Build base response mode instructions without model-specific intro text
 * Models should add their own intro text if needed
 */
export function buildResponseModeInstruction(
  mode: ResponseMode | undefined,
  modelDisplayName: string,
  options?: {
    introText?: string;
  }
): string {
  const { introText = "" } = options || {};
  const intro = introText ? `${introText} ` : "";

  const quickModeContent = `${intro}Respond in a brief, concise manner:
- Give short, direct answers (2-3 sentences max for simple questions)
- Use bullet points for lists instead of paragraphs
- Skip lengthy explanations unless specifically asked
- Get straight to the point
- Only elaborate if the question requires detailed explanation

${FORMATTING_RULES}

${MULTI_AGENT_CONTEXT}

Your name is [${modelDisplayName}].${PREFIX_FORBIDDEN_INSTRUCTION}`;

  const detailedModeContent = `${intro}Provide balanced, moderately detailed responses:
- Give clear explanations with enough context to be useful
- Use a mix of paragraphs and bullet points as appropriate
- Include key details but avoid excessive elaboration
- Aim for 1-3 short paragraphs for typical questions
- Provide examples when they add value, but keep them brief

${FORMATTING_RULES}

${MULTI_AGENT_CONTEXT}

Your name is [${modelDisplayName}].${PREFIX_FORBIDDEN_INSTRUCTION}`;

  switch (mode) {
    case 'quick':
      return quickModeContent;
    default:
      return detailedModeContent;
  }
}

/**
 * Build time context string
 * Uses UTC time for consistency and cacheability
 */
export function buildTimeContext(location?: string): string {
  const now = new Date();
  let timeContext = `Current UTC time: ${now.toISOString()}`;

  if (location) {
    timeContext += `\nUser Location (lat,lng): ${location}`;
  }

  return timeContext;
}

/**
 * Build generic grounding instructions
 * Models should customize this based on their specific search capabilities
 */
export function buildGroundingInstructions(
  isFirstMessage: boolean,
  searchToolName: string = "search"
): string {
  return isFirstMessage
    ? `\n\nIMPORTANT: Use ${searchToolName} to ensure real-world facts are accurate and up-to-date. Provide inline citations for factual information. For creative or subjective parts, citations are not required. NEVER include a 'Citations' list at the bottom.`
    : `\n\nIMPORTANT: Use ${searchToolName} primarily for fact-checking real-world details. If you state facts, verify them and provide inline citations. For creative tasks or conversation, use it only when needing current information. NEVER include a 'Citations' list at the bottom.`;
}

/**
 * Build tool-specific instructions (for internet_search, etc.)
 */
export function buildInternetSearchInstructions(): string {
  return `\n\nTOOL USE: You have access to an 'internet_search' tool.
- Use it to find up-to-date information AND to fact-check claims before presenting them.
- When the user asks a factual question, verify the answer using this tool before responding — do not rely solely on your training data.
- You can accept multiple queries; break down complex questions into sub-queries.
- CITATION RULE: When you use information from the search results, you MUST provide inline citations.
- Format: [source](URL) - the word 'source' is fixed, do NOT use the page title.
- Place the full stop BEFORE the citation, not after.
- Example: "The population of Paris is 2.1 million. [source](https://en.wikipedia.org/wiki/Paris)"
- Do not list sources at the end; link them inline where the fact is stated.`;
}

/**
 * Build citation rule reminder for XAI when using internet_search
 */
export function buildCitationRuleReminder(): string {
  return `\n\n(CITATION RULE: When using 'internet_search', you MUST cite sources inline using the format [source](URL). The word 'source' is FIXED. Do NOT use the title. Place the full stop BEFORE the citation. Example: "The sky is blue. [source](https://example.com)" Do NOT create a separate reference list.)`;
}

/**
 * Build the prefix reminder to append to user messages
 */
export function buildPrefixReminder(modelDisplayName: string): string {
  return `\n\n(STRICT REMINDER: Do NOT prefix your response with your name or [${modelDisplayName}]:. Just start with the content.)`;
}

/**
 * Build grounding reminder to prepend to user messages
 */
export function buildGroundingReminder(): string {
  return `(GROUNDING ENABLED: Use Google Search for fact-checking real-world information. For creative or conversation tasks, use it only as needed. NEVER include a 'Citations' list at the bottom.)\n\n`;
}

// === Context Injection for Conversations ===

/**
 * Build upcoming events context prompt
 */
export function buildEventsContextPrompt(eventsContext: string): string {
  return `UPCOMING EVENTS (next few only — there may be more events beyond these):
${eventsContext}

IMPORTANT DISPLAY RULES:
- All event times above are in UTC (ISO 8601 format with Z suffix)
- When showing events to the user, convert these UTC times to their local timezone based on their location
- Display times in natural, user-friendly format (e.g., "Tuesday, Feb 3 at 3:00 PM")
- Do NOT show event IDs, UTC times, or timezone abbreviations unless specifically requested
- Do not explicitly mention that you are reading from an events list unless relevant
- These are only the nearest upcoming events, NOT the complete list. There may be additional events after the last one shown. If the user asks about events beyond this range, use the event tools (get_upcoming_events, get_events_by_date_range, search_events) to fetch more.`;
}

/**
 * Build timezone handling instructions
 */
export function buildTimezoneInstructions(): string {
  return `TIMEZONE HANDLING FOR EVENTS:
- All event times are stored in UTC in the database
- When the user provides a time WITHOUT a timezone (e.g., "tomorrow at 3pm", "Feb 15 at 2:30pm"), interpret it as their local timezone and convert to UTC before storing
- When DISPLAYING event times to the user, ALWAYS convert from UTC to their local timezone
- When creating or updating events, ensure all datetime values end with 'Z' to indicate UTC
- Example: User says "meeting tomorrow at 2pm" → convert 2pm in their timezone to UTC, store as "YYYY-MM-DDTHH:MM:SSZ"
- When showing this event back, convert the UTC time to their local time for display`;
}

/**
 * Build user memory context prompt
 */
export function buildUserMemoryPrompt(memoryText: string): string {
  return `USER MEMORY (Personal Details & Preferences):\n${memoryText}\n\n(Use this information to personalize your response, but do not explicitly mention that you are reading from a memory file unless relevant.)`;
}

/**
 * Build document context prompt
 */
export function buildDocumentContextPrompt(documents: Array<{ title: string; content: string }>): string {
  const contextParts = documents.map(doc => `Context from document "${doc.title}":\n\n${doc.content}`);
  return contextParts.join('\n\n---\n\n') + `\n\nWarning: The above content is from internal documents specific to this conversation. Answer the user's questions based on this context if relevant.`;
}

/**
 * Build user facts context prompt (auto-extracted from conversations)
 */
export function buildFactsContextPrompt(facts: Array<{ category: string; fact: string }>): string {
  const grouped: Record<string, string[]> = {};
  for (const f of facts) {
    if (!grouped[f.category]) grouped[f.category] = [];
    grouped[f.category].push(f.fact);
  }

  let text = 'USER FACTS (Auto-extracted from conversations):\n';
  for (const [category, items] of Object.entries(grouped)) {
    text += `\n[${category}]\n`;
    for (const item of items) {
      text += `- ${item}\n`;
    }
  }
  text += '\n(These facts were auto-extracted from past conversations. Use them for context, but if they conflict with USER MEMORY above, prefer USER MEMORY as it is more accurate and curated.)';
  return text;
}

/**
 * Build recent conversations context prompt
 */
export function buildRecentConversationsPrompt(
  conversations: Array<{ title: string; userMessages: string[] }>
): string {
  let text = 'RECENT CONVERSATIONS (Last few conversations for context):\n';
  for (const conv of conversations) {
    text += `\n[${conv.title}]\n`;
    for (const msg of conv.userMessages) {
      text += `- ${msg}\n`;
    }
  }
  text += '\n(Use for context continuity, but don\'t proactively reference unless the user brings up a related topic.)';
  return text;
}

/**
 * Build RAG facts context prompt (semantically matched facts for the current message)
 */
export function buildRagFactsContextPrompt(
  facts: Array<{ fact: string; category: string; distance: number; last_extracted_at: string | null }>
): string {
  let text = 'POSSIBLY RELATED FACTS (Semantic search results based on the current message):\n\n';
  for (const f of facts) {
    const timeInfo = f.last_extracted_at
      ? ` (last extracted: ${f.last_extracted_at})`
      : '';
    text += `- [${f.category}] ${f.fact}${timeInfo}\n`;
  }
  text += '\nIMPORTANT: These facts were found via semantic text matching and could be completely unrelated to the current question — do NOT assume relevance. Only use a fact if it clearly and directly applies. Also consider the extraction time — older facts may be outdated.';
  return text;
}

/**
 * Build acknowledgement message for context injection
 */
export function buildContextAcknowledgement(contextType: 'events' | 'timezone' | 'memory' | 'facts' | 'ragFacts' | 'recentConversations' | 'documents'): string {
  switch (contextType) {
    case 'events':
      return "I have noted your upcoming events and will convert times to your local timezone.";
    case 'timezone':
      return "I understand the timezone handling requirements.";
    case 'memory':
      return "I have noted your personal details and preferences.";
    case 'facts':
      return "I have noted the user facts and will use them for context.";
    case 'ragFacts':
      return "I have noted the possibly related facts and will consider them if relevant.";
    case 'recentConversations':
      return "I have noted the recent conversation topics.";
    case 'documents':
      return "I understand. I will use the provided document context to answer your questions.";
  }
}
